{% set name = "featurewiz" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b74bd71b45f950fb2ffdab8ea3cfbbc585fd0f6fef80c57f928df8e4ca0eda45

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - category_encoders
    - dask-core >=2021.11.0
    - distributed >=2021.11.0
    - feather-format >=0.4.1
    - fsspec >=0.3.3
    - imbalanced-learn >=0.7
    - ipython
    - jupyter
    - lightgbm >=3.2.1
    - matplotlib-base
    - networkx
    - pandas >=1.3.4
    - pillow <=9.0.0
    - pyarrow ==7.0.0
    - python >=3.7
    - scikit-learn >=0.23.2
    - seaborn
    - tqdm
    - xgboost >=1.5.1
    - xlrd

test:
  imports:
    - featurewiz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AutoViML/featurewiz
  summary: Select Best Features from your data set - any size - now with XGBoost!
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - arturdaraujo
